python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 8
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 1
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 2
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 4
python regression_two_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 8
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 1
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 2
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 4
python regression_two_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 0  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 128 --neighbor 1  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 0  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler shadow --hidden 256 --neighbor 1  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-products --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 8
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 1
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 2
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 4
python regression_three_test.py --model sage --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 0  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 128 --neighbor 1  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 0  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler shadow --hidden 256 --neighbor 1  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 0  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 128 --neighbor 1  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 0  --cpu_process 8
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 1
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 2
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 4
python regression_three_test.py --model gcn --dataset  ogbn-papers100M --sampler neighbor --hidden 256 --neighbor 1  --cpu_process 8