#!/bin/bash
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 14
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 1 --n_trainer 15
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 2 --n_trainer 14
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 3 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 4 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 5 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 6 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 6 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 6 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 6 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 6 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 6 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 6 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 6 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 7 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 7 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 7 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 7 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 7 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 7 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 7 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 7 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 8 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 8 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 8 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 8 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 8 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 8 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 8 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 2 --n_sampler 8 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 1 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 1 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 2 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 2 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 3 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 3 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 4 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 4 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 5 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 5 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 6 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 6 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 7 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 7 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 8 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 3 --n_sampler 8 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 4 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 5 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 6 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 6 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 6 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 6 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 6 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 6 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 6 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 6 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 6 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 6 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 7 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 7 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 7 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 7 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 7 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 7 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 8 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 8 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 8 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 8 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 8 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset ogbn-products --cpu_process 8 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 14
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 1 --n_trainer 15
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 2 --n_trainer 14
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 3 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 4 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 5 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 6 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 6 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 6 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 6 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 6 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 6 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 6 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 6 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 7 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 7 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 7 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 7 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 7 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 7 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 7 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 7 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 8 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 8 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 8 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 8 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 8 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 8 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 8 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 2 --n_sampler 8 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 1 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 1 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 2 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 2 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 3 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 3 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 4 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 4 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 5 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 5 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 6 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 6 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 7 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 7 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 8 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 3 --n_sampler 8 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 4 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 5 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 6 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 6 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 6 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 6 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 6 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 6 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 6 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 6 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 6 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 6 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 7 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 7 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 7 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 7 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 7 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 7 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 8 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 8 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 8 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 8 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 8 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset flickr --cpu_process 8 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 14
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 1 --n_trainer 15
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 2 --n_trainer 14
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 3 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 4 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 5 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 6 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 6 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 6 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 6 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 6 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 6 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 6 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 6 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 7 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 7 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 7 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 7 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 7 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 7 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 7 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 7 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 8 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 8 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 8 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 8 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 8 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 8 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 8 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 2 --n_sampler 8 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 1 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 1 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 2 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 2 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 3 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 3 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 4 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 4 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 5 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 5 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 6 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 6 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 7 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 7 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 8 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 3 --n_sampler 8 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 4 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 5 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 6 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 6 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 6 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 6 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 6 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 6 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 6 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 6 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 6 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 6 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 7 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 7 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 7 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 7 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 7 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 7 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 8 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 8 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 8 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 8 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 8 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset reddit --cpu_process 8 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 14
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 1 --n_trainer 15
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 2 --n_trainer 14
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 3 --n_trainer 13
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 4 --n_trainer 12
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 5 --n_trainer 11
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 6 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 6 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 6 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 6 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 6 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 6 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 6 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 6 --n_trainer 10
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 7 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 7 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 7 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 7 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 7 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 7 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 7 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 7 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 8 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 8 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 8 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 8 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 8 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 8 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 8 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 2 --n_sampler 8 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 1 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 1 --n_trainer 9
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 2 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 2 --n_trainer 8
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 3 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 3 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 4 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 4 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 5 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 5 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 6 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 6 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 7 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 7 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 8 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 3 --n_sampler 8 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 1 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 1 --n_trainer 7
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 2 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 2 --n_trainer 6
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 3 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 3 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 4 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 4 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 5 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 5 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 6 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 6 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 4 --n_sampler 7 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 1 --n_trainer 5
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 2 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 3 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 4 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 5 --n_sampler 5 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 6 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 6 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 6 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 6 --n_sampler 1 --n_trainer 4
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 6 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 6 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 6 --n_sampler 2 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 6 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 6 --n_sampler 3 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 6 --n_sampler 4 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 7 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 7 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 7 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 7 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 7 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 7 --n_sampler 3 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 8 --n_sampler 1 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 8 --n_sampler 1 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 8 --n_sampler 1 --n_trainer 3
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 8 --n_sampler 2 --n_trainer 1
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 8 --n_sampler 2 --n_trainer 2
timeout 5400 python -W ignore PyG/gnn_train2.py --dataset yelp --cpu_process 8 --n_sampler 3 --n_trainer 1